export const WE_ARE_ALT_WORLD_INSTAGRAM = 'https://www.instagram.com/wearealtworld/?hl=en-gb'
export const WE_ARE_ALT_STUDIO_INSTAGRAM = 'https://www.instagram.com/wearealtstudios/?hl=en-gb'

export const imageFolder = '/images'
export const videoFolder = '/videos'

// Image slideshow
export const SLIDESHOW_SCROLL_SPEED = 0.25

const slideshowFolder = `${imageFolder}/slideshow`
const studioSlideshowFolder = `${slideshowFolder}/studio`
const platformSlideshowFolder = `${slideshowFolder}/platform`

export const STUDIO_SLIDESHOW_IMAGES = [
  { src: `${studioSlideshowFolder}/01.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/02.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/03.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/04.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/05.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/06.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/07.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/08.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/09.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/10.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/11.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/12.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/13.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/14.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/15.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/16.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/17.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/18.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/19.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/20.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/21.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/22.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/23.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/24.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/25.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/26.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/27.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/28.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/29.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/30.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/31.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/32.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/33.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/34.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/35.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/36.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/37.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/38.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/39.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/40.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/41.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/42.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/43.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/44.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/45.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/46.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/47.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/48.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/49.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/50.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/51.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/52.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/53.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/54.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/55.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/56.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/57.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/58.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/59.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/60.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/61.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/62.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/63.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/64.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/65.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/66.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/67.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/68.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/69.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/70.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/71.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/72.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/73.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/74.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/75.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/76.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/77.webp`, alt: '' },
  { src: `${studioSlideshowFolder}/78.webp`, alt: '' },
]

export const PLATFORM_SLIDESHOW_IMAGES = [
  { src: `${platformSlideshowFolder}/01.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/02.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/03.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/04.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/05.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/06.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/07.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/08.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/09.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/10.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/11.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/12.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/13.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/14.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/15.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/16.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/17.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/18.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/19.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/20.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/21.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/22.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/23.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/24.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/25.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/26.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/27.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/28.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/29.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/30.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/31.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/32.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/33.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/34.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/35.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/36.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/37.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/38.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/39.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/40.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/41.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/42.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/43.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/44.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/45.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/46.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/47.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/48.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/49.webp`, alt: '' },
  { src: `${platformSlideshowFolder}/50.webp`, alt: '' },
]
