export const WE_ARE_ALT_WORLD_INSTAGRAM = 'https://www.instagram.com/wearealtworld/?hl=en-gb'
export const WE_ARE_ALT_STUDIO_INSTAGRAM = 'https://www.instagram.com/wearealtstudios/?hl=en-gb'

// Image slideshow
const slideshowFolder = '/images/slideshow/'
const studioSlideshowFolder = `${slideshowFolder}studio/`
const platformSlideshowFolder = `${slideshowFolder}platform/`

export const SCROLL_SPEED = 0.25

export const SLIDESHOW_IMAGES = [
  { src: `${slideshowFolder}01.webp`, alt: '' },
  { src: `${slideshowFolder}02.webp`, alt: '' },
  { src: `${slideshowFolder}03.webp`, alt: '' },
  { src: `${slideshowFolder}04.webp`, alt: '' },
  { src: `${slideshowFolder}05.webp`, alt: '' },
  { src: `${slideshowFolder}06.webp`, alt: '' },
  { src: `${slideshowFolder}07.webp`, alt: '' },
  { src: `${slideshowFolder}08.webp`, alt: '' },
  { src: `${slideshowFolder}09.webp`, alt: '' },
  { src: `${slideshowFolder}10.webp`, alt: '' },
  { src: `${slideshowFolder}11.webp`, alt: '' },
  { src: `${slideshowFolder}12.webp`, alt: '' },
  { src: `${slideshowFolder}13.webp`, alt: '' },
  { src: `${slideshowFolder}14.webp`, alt: '' },
  { src: `${slideshowFolder}15.webp`, alt: '' },
  { src: `${slideshowFolder}16.webp`, alt: '' },
  { src: `${slideshowFolder}17.webp`, alt: '' },
  { src: `${slideshowFolder}18.webp`, alt: '' },
  { src: `${slideshowFolder}19.webp`, alt: '' },
  { src: `${slideshowFolder}20.webp`, alt: '' },
  { src: `${slideshowFolder}21.webp`, alt: '' },
  { src: `${slideshowFolder}22.webp`, alt: '' },
  { src: `${slideshowFolder}23.webp`, alt: '' },
  { src: `${slideshowFolder}24.webp`, alt: '' },
  { src: `${slideshowFolder}25.webp`, alt: '' },
  { src: `${slideshowFolder}26.webp`, alt: '' },
  { src: `${slideshowFolder}27.webp`, alt: '' },
  { src: `${slideshowFolder}28.webp`, alt: '' },
  { src: `${slideshowFolder}29.webp`, alt: '' },
  { src: `${slideshowFolder}30.webp`, alt: '' },
  { src: `${slideshowFolder}31.webp`, alt: '' },
  { src: `${slideshowFolder}32.webp`, alt: '' },
  { src: `${slideshowFolder}33.webp`, alt: '' },
  { src: `${slideshowFolder}34.webp`, alt: '' },
  { src: `${slideshowFolder}35.webp`, alt: '' },
  { src: `${slideshowFolder}36.webp`, alt: '' },
  { src: `${slideshowFolder}37.webp`, alt: '' },
  { src: `${slideshowFolder}38.webp`, alt: '' },
  { src: `${slideshowFolder}39.webp`, alt: '' },
  { src: `${slideshowFolder}40.webp`, alt: '' },
  { src: `${slideshowFolder}41.webp`, alt: '' },
  { src: `${slideshowFolder}42.webp`, alt: '' },
  { src: `${slideshowFolder}43.webp`, alt: '' },
  { src: `${slideshowFolder}44.webp`, alt: '' },
  { src: `${slideshowFolder}45.webp`, alt: '' },
  { src: `${slideshowFolder}46.webp`, alt: '' },
  { src: `${slideshowFolder}47.webp`, alt: '' },
  { src: `${slideshowFolder}48.webp`, alt: '' },
  { src: `${slideshowFolder}49.webp`, alt: '' },
  { src: `${slideshowFolder}50.webp`, alt: '' },
  { src: `${slideshowFolder}51.webp`, alt: '' },
  { src: `${slideshowFolder}52.webp`, alt: '' },
  { src: `${slideshowFolder}53.webp`, alt: '' },
  { src: `${slideshowFolder}54.webp`, alt: '' },
  { src: `${slideshowFolder}55.webp`, alt: '' },
  { src: `${slideshowFolder}56.webp`, alt: '' },
  { src: `${slideshowFolder}57.webp`, alt: '' },
  { src: `${slideshowFolder}58.webp`, alt: '' },
  { src: `${slideshowFolder}59.webp`, alt: '' },
  { src: `${slideshowFolder}60.webp`, alt: '' },
  { src: `${slideshowFolder}61.webp`, alt: '' },
  { src: `${slideshowFolder}62.webp`, alt: '' },
  { src: `${slideshowFolder}63.webp`, alt: '' },
]

export const STUDIO_SLIDESHOW_IMAGES = [
  { src: `${studioSlideshowFolder}01.webp`, alt: '' },
  { src: `${studioSlideshowFolder}02.webp`, alt: '' },
  { src: `${studioSlideshowFolder}03.webp`, alt: '' },
  { src: `${studioSlideshowFolder}04.webp`, alt: '' },
  { src: `${studioSlideshowFolder}05.webp`, alt: '' },
  { src: `${studioSlideshowFolder}06.webp`, alt: '' },
  { src: `${studioSlideshowFolder}07.webp`, alt: '' },
  { src: `${studioSlideshowFolder}08.webp`, alt: '' },
  { src: `${studioSlideshowFolder}09.webp`, alt: '' },
  { src: `${studioSlideshowFolder}10.webp`, alt: '' },
  { src: `${studioSlideshowFolder}11.webp`, alt: '' },
  { src: `${studioSlideshowFolder}12.webp`, alt: '' },
  { src: `${studioSlideshowFolder}13.webp`, alt: '' },
  { src: `${studioSlideshowFolder}14.webp`, alt: '' },
  { src: `${studioSlideshowFolder}15.webp`, alt: '' },
  { src: `${studioSlideshowFolder}16.webp`, alt: '' },
  { src: `${studioSlideshowFolder}17.webp`, alt: '' },
  { src: `${studioSlideshowFolder}18.webp`, alt: '' },
  { src: `${studioSlideshowFolder}19.webp`, alt: '' },
  { src: `${studioSlideshowFolder}20.webp`, alt: '' },
  { src: `${studioSlideshowFolder}21.webp`, alt: '' },
  { src: `${studioSlideshowFolder}22.webp`, alt: '' },
  { src: `${studioSlideshowFolder}23.webp`, alt: '' },
  { src: `${studioSlideshowFolder}24.webp`, alt: '' },
  { src: `${studioSlideshowFolder}25.webp`, alt: '' },
  { src: `${studioSlideshowFolder}26.webp`, alt: '' },
  { src: `${studioSlideshowFolder}27.webp`, alt: '' },
  { src: `${studioSlideshowFolder}28.webp`, alt: '' },
  { src: `${studioSlideshowFolder}29.webp`, alt: '' },
  { src: `${studioSlideshowFolder}30.webp`, alt: '' },
  { src: `${studioSlideshowFolder}31.webp`, alt: '' },
  { src: `${studioSlideshowFolder}32.webp`, alt: '' },
  { src: `${studioSlideshowFolder}33.webp`, alt: '' },
  { src: `${studioSlideshowFolder}34.webp`, alt: '' },
  { src: `${studioSlideshowFolder}35.webp`, alt: '' },
  { src: `${studioSlideshowFolder}36.webp`, alt: '' },
  { src: `${studioSlideshowFolder}37.webp`, alt: '' },
  { src: `${studioSlideshowFolder}38.webp`, alt: '' },
  { src: `${studioSlideshowFolder}39.webp`, alt: '' },
  { src: `${studioSlideshowFolder}40.webp`, alt: '' },
  { src: `${studioSlideshowFolder}41.webp`, alt: '' },
  { src: `${studioSlideshowFolder}42.webp`, alt: '' },
  { src: `${studioSlideshowFolder}43.webp`, alt: '' },
  { src: `${studioSlideshowFolder}44.webp`, alt: '' },
  { src: `${studioSlideshowFolder}45.webp`, alt: '' },
  { src: `${studioSlideshowFolder}46.webp`, alt: '' },
  { src: `${studioSlideshowFolder}47.webp`, alt: '' },
]

export const PLATFORM_SLIDESHOW_IMAGES = [
  { src: `${platformSlideshowFolder}01.webp`, alt: '' },
  { src: `${platformSlideshowFolder}02.webp`, alt: '' },
  { src: `${platformSlideshowFolder}03.webp`, alt: '' },
  { src: `${platformSlideshowFolder}04.webp`, alt: '' },
  { src: `${platformSlideshowFolder}05.webp`, alt: '' },
  { src: `${platformSlideshowFolder}06.webp`, alt: '' },
  { src: `${platformSlideshowFolder}07.webp`, alt: '' },
  { src: `${platformSlideshowFolder}08.webp`, alt: '' },
  { src: `${platformSlideshowFolder}09.webp`, alt: '' },
  { src: `${platformSlideshowFolder}10.webp`, alt: '' },
  { src: `${platformSlideshowFolder}11.webp`, alt: '' },
  { src: `${platformSlideshowFolder}12.webp`, alt: '' },
  { src: `${platformSlideshowFolder}13.webp`, alt: '' },
  { src: `${platformSlideshowFolder}14.webp`, alt: '' },
  { src: `${platformSlideshowFolder}15.webp`, alt: '' },
  { src: `${platformSlideshowFolder}16.webp`, alt: '' },
  { src: `${platformSlideshowFolder}17.webp`, alt: '' },
  { src: `${platformSlideshowFolder}18.webp`, alt: '' },
  { src: `${platformSlideshowFolder}19.webp`, alt: '' },
  { src: `${platformSlideshowFolder}20.webp`, alt: '' },
  { src: `${platformSlideshowFolder}21.webp`, alt: '' },
  { src: `${platformSlideshowFolder}22.webp`, alt: '' },
  { src: `${platformSlideshowFolder}23.webp`, alt: '' },
  { src: `${platformSlideshowFolder}24.webp`, alt: '' },
  { src: `${platformSlideshowFolder}25.webp`, alt: '' },
  { src: `${platformSlideshowFolder}26.webp`, alt: '' },
  { src: `${platformSlideshowFolder}27.webp`, alt: '' },
  { src: `${platformSlideshowFolder}28.webp`, alt: '' },
  { src: `${platformSlideshowFolder}29.webp`, alt: '' },
  { src: `${platformSlideshowFolder}30.webp`, alt: '' },
  { src: `${platformSlideshowFolder}31.webp`, alt: '' },
  { src: `${platformSlideshowFolder}32.webp`, alt: '' },
  { src: `${platformSlideshowFolder}33.webp`, alt: '' },
  { src: `${platformSlideshowFolder}34.webp`, alt: '' },
  { src: `${platformSlideshowFolder}35.webp`, alt: '' },
  { src: `${platformSlideshowFolder}36.webp`, alt: '' },
  { src: `${platformSlideshowFolder}37.webp`, alt: '' },
  { src: `${platformSlideshowFolder}38.webp`, alt: '' },
  { src: `${platformSlideshowFolder}39.webp`, alt: '' },
  { src: `${platformSlideshowFolder}40.webp`, alt: '' },
]
