export const WE_ARE_ALT_WORLD_INSTAGRAM = 'https://www.instagram.com/wearealtworld/?hl=en-gb'
export const WE_ARE_ALT_STUDIO_INSTAGRAM = WE_ARE_ALT_WORLD_INSTAGRAM

// Image slideshow
const slideshowFolder = '/images/slideshow/'

export const SCROLL_SPEED = 0.25

export const SLIDESHOW_IMAGES = [
  { src: `${slideshowFolder}01.webp`, alt: '' },
  { src: `${slideshowFolder}02.webp`, alt: '' },
  { src: `${slideshowFolder}03.webp`, alt: '' },
  { src: `${slideshowFolder}04.webp`, alt: '' },
  { src: `${slideshowFolder}05.webp`, alt: '' },
  { src: `${slideshowFolder}06.webp`, alt: '' },
  { src: `${slideshowFolder}07.webp`, alt: '' },
  { src: `${slideshowFolder}08.webp`, alt: '' },
  { src: `${slideshowFolder}09.webp`, alt: '' },
  { src: `${slideshowFolder}10.webp`, alt: '' },
  { src: `${slideshowFolder}11.webp`, alt: '' },
  { src: `${slideshowFolder}12.webp`, alt: '' },
  { src: `${slideshowFolder}13.webp`, alt: '' },
  { src: `${slideshowFolder}14.webp`, alt: '' },
  { src: `${slideshowFolder}15.webp`, alt: '' },
  { src: `${slideshowFolder}16.webp`, alt: '' },
  { src: `${slideshowFolder}17.webp`, alt: '' },
  { src: `${slideshowFolder}18.webp`, alt: '' },
  { src: `${slideshowFolder}19.webp`, alt: '' },
  { src: `${slideshowFolder}20.webp`, alt: '' },
  { src: `${slideshowFolder}21.webp`, alt: '' },
  { src: `${slideshowFolder}22.webp`, alt: '' },
  { src: `${slideshowFolder}23.webp`, alt: '' },
  { src: `${slideshowFolder}24.webp`, alt: '' },
  { src: `${slideshowFolder}25.webp`, alt: '' },
  { src: `${slideshowFolder}26.webp`, alt: '' },
  { src: `${slideshowFolder}27.webp`, alt: '' },
  { src: `${slideshowFolder}28.webp`, alt: '' },
  { src: `${slideshowFolder}29.webp`, alt: '' },
  { src: `${slideshowFolder}30.webp`, alt: '' },
  { src: `${slideshowFolder}31.webp`, alt: '' },
  { src: `${slideshowFolder}32.webp`, alt: '' },
  { src: `${slideshowFolder}33.webp`, alt: '' },
  { src: `${slideshowFolder}34.webp`, alt: '' },
  { src: `${slideshowFolder}35.webp`, alt: '' },
  { src: `${slideshowFolder}36.webp`, alt: '' },
  { src: `${slideshowFolder}37.webp`, alt: '' },
  { src: `${slideshowFolder}38.webp`, alt: '' },
  { src: `${slideshowFolder}39.webp`, alt: '' },
  { src: `${slideshowFolder}40.webp`, alt: '' },
  { src: `${slideshowFolder}41.webp`, alt: '' },
  { src: `${slideshowFolder}42.webp`, alt: '' },
  { src: `${slideshowFolder}43.webp`, alt: '' },
  { src: `${slideshowFolder}44.webp`, alt: '' },
  { src: `${slideshowFolder}45.webp`, alt: '' },
  { src: `${slideshowFolder}46.webp`, alt: '' },
  { src: `${slideshowFolder}47.webp`, alt: '' },
  { src: `${slideshowFolder}48.webp`, alt: '' },
  { src: `${slideshowFolder}49.webp`, alt: '' },
  { src: `${slideshowFolder}50.webp`, alt: '' },
  { src: `${slideshowFolder}51.webp`, alt: '' },
  { src: `${slideshowFolder}52.webp`, alt: '' },
  { src: `${slideshowFolder}53.webp`, alt: '' },
  { src: `${slideshowFolder}54.webp`, alt: '' },
  { src: `${slideshowFolder}55.webp`, alt: '' },
  { src: `${slideshowFolder}56.webp`, alt: '' },
  { src: `${slideshowFolder}57.webp`, alt: '' },
  { src: `${slideshowFolder}58.webp`, alt: '' },
  { src: `${slideshowFolder}59.webp`, alt: '' },
  { src: `${slideshowFolder}60.webp`, alt: '' },
  { src: `${slideshowFolder}61.webp`, alt: '' },
  { src: `${slideshowFolder}62.webp`, alt: '' },
  { src: `${slideshowFolder}63.webp`, alt: '' },
]
